# Generated by Django 3.1.6 on 2021-03-26 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.JSONField()),
                ('object', models.TextField()),
                ('object_type', models.CharField(choices=[('comment', 'comment'), ('post', 'post')], max_length=8)),
                ('object_id', models.TextField()),
                ('author_id', models.CharField(max_length=40)),
            ],
            options={
                'unique_together': {('author', 'object')},
            },
        ),
    ]
