# Generated by Django 3.1.6 on 2021-03-26 18:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.JSONField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('contentType', models.CharField(choices=[('Text', (('text/markdown', 'markdown'), ('text/plain', 'plain'), ('text/html', 'html'))), ('Encoded Text', (('application/base64', 'base64'),)), ('Image', (('image/png;base64', '.png'), ('image/jpeg;base64', '.jpg')))], default='text/markdown', max_length=18)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
