# Generated by Django 3.1.6 on 2021-03-23 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_followers_remotefollowers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='remoteFollowers',
            field=models.JSONField(default=dict),
        ),
    ]
