name: Run Python Tests
on: [push]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🐍 Install Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: 🛠 Install dependencies
        working-directory: ./server 
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: 📝 Run Django testing
        working-directory: ./server
        run: |
          python manage.py test